name = "global-pilot-academy"
compatibility_date = "2024-09-02"

# Pages configuration for static site deployment
pages_build_output_dir = ".vercel/output/static"

# Environment variables (if needed)
[vars]
NODE_VERSION = "18"
